name: Build Rust

on: [push, pull_request]

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: 1.58
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
